"""Add is_read

Revision ID: 188a4a37868a
Revises: 9db481e61abb
Create Date: 2026-03-09 16:50:36.337562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188a4a37868a'
down_revision: Union[str, Sequence[str], None] = '9db481e61abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_chat_events', sa.Column('is_read', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_chat_events', 'is_read')
    # ### end Alembic commands ###
