"""Delete recipient_role.

Revision ID: 31c851c306e9
Revises: b2c4f8a1d9e3
Create Date: 2026-03-09 01:22:57.498015

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "31c851c306e9"
down_revision: str | Sequence[str] | None = "b2c4f8a1d9e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking_email_notifications", "recipient_role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking_email_notifications", sa.Column("recipient_role", sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
