"""Change booking_id to nullable

Revision ID: 3a791de67f88
Revises: 5f1c2e9a8b1d
Create Date: 2026-03-03 22:06:40.465434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a791de67f88'
down_revision: Union[str, Sequence[str], None] = '5f1c2e9a8b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'booking_id',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'booking_id',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
