"""Delete recipient_role

Revision ID: 4c0ec66f1c56
Revises: 31c851c306e9
Create Date: 2026-03-09 01:35:52.151451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0ec66f1c56'
down_revision: Union[str, Sequence[str], None] = '31c851c306e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_bml_booking_ref_id_recipient_role'), 'booking_meeting_links', type_='unique')
    op.create_unique_constraint('uq_bml_booking_ref_id_participant_ref_id', 'booking_meeting_links', ['booking_ref_id', 'participant_ref_id'])
    op.drop_column('booking_meeting_links', 'recipient_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_meeting_links', sa.Column('recipient_role', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_bml_booking_ref_id_participant_ref_id', 'booking_meeting_links', type_='unique')
    op.create_unique_constraint(op.f('uq_bml_booking_ref_id_recipient_role'), 'booking_meeting_links', ['booking_ref_id', 'recipient_role'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
