"""Delete recipient_role

Revision ID: 9db481e61abb
Revises: 4c0ec66f1c56
Create Date: 2026-03-09 01:37:57.643947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db481e61abb'
down_revision: Union[str, Sequence[str], None] = '4c0ec66f1c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_telegram_notifications', 'recipient_role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking_telegram_notifications', sa.Column('recipient_role', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
