"""Add start_time and end_time

Revision ID: afce66b11b80
Revises: b0e296cc4b17
Create Date: 2026-03-09 19:55:44.272366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afce66b11b80'
down_revision: Union[str, Sequence[str], None] = 'b0e296cc4b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('start_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('bookings', sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'end_time')
    op.drop_column('bookings', 'start_time')
    # ### end Alembic commands ###
