"""Add updated_at to booking_chat_events.

Revision ID: b0e296cc4b17
Revises: 188a4a37868a
Create Date: 2026-03-09 17:15:56.067227

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b0e296cc4b17"
down_revision: str | Sequence[str] | None = "188a4a37868a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking_chat_events", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("booking_chat_events", "updated_at")
    # ### end Alembic commands ###
